### ISSUE TITLE
Timer cancellation is being performed out of order during Gravatar fetch

### ISSUE THREAD

**Issue by zostay** [zostay/CPAN-Sidekick#11]
I have gotten 10 reports of this exception.

```
java.lang.RuntimeException: Gravatar took too long
at com.qubling.sidekick.fetch.other.GravatarFetcher$1.run(GravatarFetcher.java:125)
at java.util.Timer$TimerImpl.run(Timer.java:284)
```

I set up a timer thread to cancel the Gravatar request when it takes too long. However, there is a problem with the order in which this timer is canceled which can lead to the timer still being alive at a point in which we are not prepared to catch the Runtime exception. This needs to be tightened up.

**Comment by zostay** [comment]
This problem is resolved. It cannot happen as the RuntimeException that was causing this has been removed from the app.
